from fastapi import APIRouter
from app.api.v1.endpoints import health, conversion, pdf_tools, persons, auth, users, json_conversion, website_conversion, csv_conversion, xml_conversion, office_documents_conversion, image_conversion, ocr_conversion, subtitle_conversion, text_conversion, file_formatter, ebook_conversion, video_conversion, audio_conversion, pdf_conversion

api_router = APIRouter()

api_router.include_router(health.router, prefix="/health", tags=["health"])
api_router.include_router(conversion.router, prefix="/convert", tags=["conversion"])
api_router.include_router(pdf_tools.router, prefix="/pdf", tags=["PDF Tools"])
api_router.include_router(persons.router, prefix="/persons", tags=["Persons"])
api_router.include_router(json_conversion.router, prefix="/jsonconversiontools", tags=["JSON Conversion"])
api_router.include_router(website_conversion.router, prefix="/websiteconversiontools", tags=["Website Converter"])
api_router.include_router(csv_conversion.router, prefix="/csvconversiontools", tags=["CSV Conversion"])
api_router.include_router(xml_conversion.router, prefix="/xmlconversiontools", tags=["XML Conversion"])
api_router.include_router(office_documents_conversion.router, prefix="/officedocumentsconversiontools", tags=["Office Documents Conversion"])
api_router.include_router(image_conversion.router, prefix="/imageconversiontools", tags=["Image Conversion"])
api_router.include_router(ocr_conversion.router, prefix="/ocrconversiontools", tags=["OCR Conversion"])
api_router.include_router(subtitle_conversion.router, prefix="/subtitlesconversiontools", tags=["Subtitle Conversion"])
api_router.include_router(text_conversion.router, prefix="/textconversiontools", tags=["Text Conversion"])
api_router.include_router(file_formatter.router, prefix="/fileformattertools", tags=["File Formatter"])
api_router.include_router(ebook_conversion.router, prefix="/ebookconversiontools", tags=["eBook Conversion"])
api_router.include_router(video_conversion.router, prefix="/videoconversiontools", tags=["Video Conversion"])
api_router.include_router(audio_conversion.router, prefix="/audioconversiontools", tags=["Audio Conversion"])
api_router.include_router(pdf_conversion.router, prefix="/pdfconversiontools", tags=["PDF Conversion"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
